// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package sign_out is a generated GoMock package.
package sign_out

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	"github.com/google/uuid"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// deleteRefreshTokens mocks base method.
func (m *MockRepository) deleteRefreshTokens(userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "deleteRefreshTokens", userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// deleteRefreshTokens indicates an expected call of deleteRefreshTokens.
func (mr *MockRepositoryMockRecorder) deleteRefreshTokens(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "deleteRefreshTokens", reflect.TypeOf((*MockRepository)(nil).deleteRefreshTokens), userID)
}
