// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package process_password_update is a generated GoMock package.
package process_password_update

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// updateUserPassword mocks base method.
func (m *MockRepository) updateUserPassword(userID uuid.UUID, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "updateUserPassword", userID, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// updateUserPassword indicates an expected call of updateUserPassword.
func (mr *MockRepositoryMockRecorder) updateUserPassword(userID, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "updateUserPassword", reflect.TypeOf((*MockRepository)(nil).updateUserPassword), userID, password)
}
