// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package process_email_verification is a generated GoMock package.
package process_email_verification

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// updateUserEmailVerified mocks base method.
func (m *MockRepository) updateUserEmailVerified(userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "updateUserEmailVerified", userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// updateUserEmailVerified indicates an expected call of updateUserEmailVerified.
func (mr *MockRepositoryMockRecorder) updateUserEmailVerified(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "updateUserEmailVerified", reflect.TypeOf((*MockRepository)(nil).updateUserEmailVerified), userID)
}
