apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vdm
  name: backend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: vdm-sa
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: tmp
          emptyDir: { } # ephemeral, node storage
      containers:
        - name: backend
          volumeMounts:
            - name: tmp
              mountPath: /tmp
              readOnly: false
          image: geo1796/vdm-backend@sha256:f2a1f79f6aa069ec12c56ebf76545a61cc9805a2ad7839d16bdba104d3d05691
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ "ALL" ]
          resources:
            requests:
              cpu: "150m"
              memory: "192Mi"
            limits:
              cpu: "300m"
              memory: "384Mi"
          env:
            - name: ACTIVE_PROFILE
              value: 'prod'
            - name: CLIENT_URL
              value: 'https://vigiedumensonge.gocorp.fr'
            - name: MAILER_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: mailer-secrets
                  key: MAILER_ADDRESS
            - name: MAILER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mailer-secrets
                  key: MAILER_PASSWORD
            - name: MAILER_HOST
              valueFrom:
                secretKeyRef:
                  name: mailer-secrets
                  key: MAILER_HOST
            - name: MAILER_PORT
              valueFrom:
                secretKeyRef:
                  name: mailer-secrets
                  key: MAILER_PORT
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DB_PORT
            - name: DB_SSL_MODE
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DB_SSL_MODE
            - name: PASSWORD_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: security-secrets
                  key: PASSWORD_TOKEN_SECRET
            - name: PASSWORD_TOKEN_TTL
              valueFrom:
                secretKeyRef:
                  name: security-secrets
                  key: PASSWORD_TOKEN_TTL
            - name: EMAIL_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: security-secrets
                  key: EMAIL_TOKEN_SECRET
            - name: EMAIL_TOKEN_TTL
              valueFrom:
                secretKeyRef:
                  name: security-secrets
                  key: EMAIL_TOKEN_TTL
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: security-secrets
                  key: REFRESH_TOKEN_SECRET
            - name: REFRESH_TOKEN_TTL
              valueFrom:
                secretKeyRef:
                  name: security-secrets
                  key: REFRESH_TOKEN_TTL
            - name: REFRESH_COOKIE_NAME
              valueFrom:
                secretKeyRef:
                  name: security-secrets
                  key: REFRESH_COOKIE_NAME
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: security-secrets
                  key: ACCESS_TOKEN_SECRET
            - name: ACCESS_TOKEN_TTL
              valueFrom:
                secretKeyRef:
                  name: security-secrets
                  key: ACCESS_TOKEN_TTL
            - name: ACCESS_COOKIE_NAME
              valueFrom:
                secretKeyRef:
                  name: security-secrets
                  key: ACCESS_COOKIE_NAME
            - name: CSRF_COOKIE_NAME
              valueFrom:
                secretKeyRef:
                  name: security-secrets
                  key: CSRF_COOKIE_NAME
            - name: COOKIE_SAME_SITE
              valueFrom:
                secretKeyRef:
                  name: security-secrets
                  key: COOKIE_SAME_SITE
            - name: COOKIE_SECURE
              valueFrom:
                secretKeyRef:
                  name: security-secrets
                  key: COOKIE_SECURE
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /livez
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
          startupProbe:
            httpGet:
              path: /livez
              port: 8080
            periodSeconds: 2
            failureThreshold: 30
