apiVersion: v1
kind: Service
metadata:
  namespace: vdm
  name: backend
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
    - name: backend
      protocol: TCP
      port: 8080
      targetPort: 8080
