apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vdm
  name: data-import
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: data-import
  template:
    metadata:
      labels:
        app: data-import
    spec:
      containers:
        - name: backend
          image: geo1796/vdm-data_import:0.1
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DB_PORT
            - name: DB_SSL_MODE
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DB_SSL_MODE