/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PasswordUpdateRouteImport } from './routes/password-update'
import { Route as RedactorRouteRouteImport } from './routes/redactor/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RedactorNewDraftRouteImport } from './routes/redactor/new-draft'
import { Route as RedactorArticlesRouteImport } from './routes/redactor/articles'
import { Route as RedactorEditDraftArticleIdRouteImport } from './routes/redactor/edit-draft/$articleId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordUpdateRoute = PasswordUpdateRouteImport.update({
  id: '/password-update',
  path: '/password-update',
  getParentRoute: () => rootRouteImport,
} as any)
const RedactorRouteRoute = RedactorRouteRouteImport.update({
  id: '/redactor',
  path: '/redactor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RedactorNewDraftRoute = RedactorNewDraftRouteImport.update({
  id: '/new-draft',
  path: '/new-draft',
  getParentRoute: () => RedactorRouteRoute,
} as any)
const RedactorArticlesRoute = RedactorArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => RedactorRouteRoute,
} as any)
const RedactorEditDraftArticleIdRoute =
  RedactorEditDraftArticleIdRouteImport.update({
    id: '/edit-draft/$articleId',
    path: '/edit-draft/$articleId',
    getParentRoute: () => RedactorRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/redactor': typeof RedactorRouteRouteWithChildren
  '/password-update': typeof PasswordUpdateRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/redactor/articles': typeof RedactorArticlesRoute
  '/redactor/new-draft': typeof RedactorNewDraftRoute
  '/redactor/edit-draft/$articleId': typeof RedactorEditDraftArticleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/redactor': typeof RedactorRouteRouteWithChildren
  '/password-update': typeof PasswordUpdateRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/redactor/articles': typeof RedactorArticlesRoute
  '/redactor/new-draft': typeof RedactorNewDraftRoute
  '/redactor/edit-draft/$articleId': typeof RedactorEditDraftArticleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/redactor': typeof RedactorRouteRouteWithChildren
  '/password-update': typeof PasswordUpdateRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/redactor/articles': typeof RedactorArticlesRoute
  '/redactor/new-draft': typeof RedactorNewDraftRoute
  '/redactor/edit-draft/$articleId': typeof RedactorEditDraftArticleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/redactor'
    | '/password-update'
    | '/sign-in'
    | '/sign-up'
    | '/redactor/articles'
    | '/redactor/new-draft'
    | '/redactor/edit-draft/$articleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/redactor'
    | '/password-update'
    | '/sign-in'
    | '/sign-up'
    | '/redactor/articles'
    | '/redactor/new-draft'
    | '/redactor/edit-draft/$articleId'
  id:
    | '__root__'
    | '/'
    | '/redactor'
    | '/password-update'
    | '/sign-in'
    | '/sign-up'
    | '/redactor/articles'
    | '/redactor/new-draft'
    | '/redactor/edit-draft/$articleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RedactorRouteRoute: typeof RedactorRouteRouteWithChildren
  PasswordUpdateRoute: typeof PasswordUpdateRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-update': {
      id: '/password-update'
      path: '/password-update'
      fullPath: '/password-update'
      preLoaderRoute: typeof PasswordUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redactor': {
      id: '/redactor'
      path: '/redactor'
      fullPath: '/redactor'
      preLoaderRoute: typeof RedactorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redactor/new-draft': {
      id: '/redactor/new-draft'
      path: '/new-draft'
      fullPath: '/redactor/new-draft'
      preLoaderRoute: typeof RedactorNewDraftRouteImport
      parentRoute: typeof RedactorRouteRoute
    }
    '/redactor/articles': {
      id: '/redactor/articles'
      path: '/articles'
      fullPath: '/redactor/articles'
      preLoaderRoute: typeof RedactorArticlesRouteImport
      parentRoute: typeof RedactorRouteRoute
    }
    '/redactor/edit-draft/$articleId': {
      id: '/redactor/edit-draft/$articleId'
      path: '/edit-draft/$articleId'
      fullPath: '/redactor/edit-draft/$articleId'
      preLoaderRoute: typeof RedactorEditDraftArticleIdRouteImport
      parentRoute: typeof RedactorRouteRoute
    }
  }
}

interface RedactorRouteRouteChildren {
  RedactorArticlesRoute: typeof RedactorArticlesRoute
  RedactorNewDraftRoute: typeof RedactorNewDraftRoute
  RedactorEditDraftArticleIdRoute: typeof RedactorEditDraftArticleIdRoute
}

const RedactorRouteRouteChildren: RedactorRouteRouteChildren = {
  RedactorArticlesRoute: RedactorArticlesRoute,
  RedactorNewDraftRoute: RedactorNewDraftRoute,
  RedactorEditDraftArticleIdRoute: RedactorEditDraftArticleIdRoute,
}

const RedactorRouteRouteWithChildren = RedactorRouteRoute._addFileChildren(
  RedactorRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RedactorRouteRoute: RedactorRouteRouteWithChildren,
  PasswordUpdateRoute: PasswordUpdateRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
